package net.prehistoricnaturefossils.blocks.base;

import net.minecraft.block.Block;
import net.prehistoricnaturefossils.blocks.skeletons.*;
import net.prehistoricnaturefossils.blocks.slabs.*;

import java.util.ArrayList;
import java.util.List;

public class BlockInit {

    public static final List<Block> BLOCKS = new ArrayList<Block>();

    public static final Block FOSSIL_AKMONISTION = new BlockFossilAkmonistion();
    public static final Block FOSSIL_AMPYX = new BlockFossilAmpyx();
    public static final Block FOSSIL_ANOMOLACARIS = new BlockFossilAnomalocaris();
    public static final Block FOSSIL_ANTEOSAURUS = new BlockFossilAnteosaurus();
    public static final Block FOSSIL_ARIZONASAURUS = new BlockFossilArizonasaurus();
    public static final Block FOSSIL_ARTHROPLEURA = new BlockFossilArthropleura();
    public static final Block FOSSIL_ASAPHUS = new BlockFossilAsaphus();
    public static final Block FOSSIL_BUNGARTIUS = new BlockFossilBungartius();
    public static final Block FOSSIL_CAVIRAMUS = new BlockFossilCaviramus();
    public static final Block FOSSIL_COCCOSTEUS = new BlockFossilCoccosteus();
    public static final Block FOSSIL_COTYLORHYNCHUS = new BlockFossilCotylorhynchus();
    public static final Block FOSSIL_CYAMODUS = new BlockFossilCyamodus();
    public static final Block FOSSIL_CYMBOSPONDYLUS = new BlockFossilCymbospondylus();
    public static final Block FOSSIL_DESMATOSUCHUS = new BlockFossilDesmatosuchus();
    public static final Block FOSSIL_DIMETRODON = new BlockFossilDimetrodon();
    public static final Block FOSSIL_DIPLOCAULUS = new BlockFossilDiplocaulus();
    public static final Block FOSSIL_DRYOSAURUS = new BlockFossilDryosaurus();
    public static final Block FOSSIL_DUNKLEOSTEUS = new BlockFossilDunkleosteus();
    public static final Block FOSSIL_EDAPHOSAURUS = new BlockFossilEdaphosaurus();
    public static final Block FOSSIL_EFFIGIA = new BlockFossilEffigia();
    public static final Block FOSSIL_ERYTHROSUCHUS = new BlockFossilErythrosuchus();
    public static final Block FOSSIL_ESTEMMENOSUCHUS = new BlockFossilEstemmenosuchus();
    public static final Block FOSSIL_FALCATUS = new BlockFossilFalcatus();
    public static final Block FOSSIL_GERROTHORAX = new BlockFossilGerrothorax();
    public static final Block FOSSIL_HENODUS = new BlockFossilHenodus();
    public static final Block FOSSIL_KEICHOUSAURUS = new BlockFossilKeichousaurus();
    public static final Block FOSSIL_KENTROSAURUS = new BlockFossilKentrosaurus();
    public static final Block FOSSIL_LILIENSTERNUS = new BlockFossilLiliensternus();
    public static final Block FOSSIL_LIMULID = new BlockFossilLimulid();
    public static final Block FOSSIL_LOTOSAURUS = new BlockFossilLotosaurus();
    public static final Block FOSSIL_LYSTROSAURUS = new BlockFossilLystrosaurus();
    public static final Block FOSSIL_MASTODONSAURUS = new BlockFossilMastodonsaurus();
    public static final Block FOSSIL_MEGALOSAURUS = new BlockFossilMegalosaurus();
    public static final Block FOSSIL_MEGANEURA = new BlockFossilMeganeura();
    public static final Block FOSSIL_MEGARACHNE = new BlockFossilMegarachne();
    public static final Block FOSSIL_MIXOPTERUS = new BlockFossilMixopterus();
    public static final Block FOSSIL_MOSCHOPS = new BlockFossilMoschops();
    public static final Block FOSSIL_OPHIACODON = new BlockFossilOphiacodon();
    public static final Block FOSSIL_OPHTHALMOSAURUS = new BlockFossilOphthalmosaurus();
    public static final Block FOSSIL_PLATYHYSTRIX = new BlockFossilPlatyhystrix();
    public static final Block FOSSIL_POPOSAURUS = new BlockFossilPoposaurus();
    public static final Block FOSSIL_PRIONOSUCHUS = new BlockFossilPrionosuchus();
    public static final Block FOSSIL_PULMONOSCORPIUS = new BlockFossilPulmonoscorpius();
    public static final Block FOSSIL_RUBIDGEA = new BlockFossilRubidgea();
    public static final Block FOSSIL_SCHINDERHANNES = new BlockFossilSchinderhannes();
    public static final Block FOSSIL_SCUTOSAURUS = new BlockFossilScutosaurus();
    public static final Block FOSSIL_SHRINGASAURUS = new BlockFossilShringasaurus();
    public static final Block FOSSIL_SILESAURUS = new BlockFossilSilesaurus();
    public static final Block FOSSIL_SUMINIA = new BlockFossilSuminia();
    public static final Block FOSSIL_TANYSTROPHEUS = new BlockFossilTanystropheus();
    public static final Block FOSSIL_THECODONTOSAURUS = new BlockFossilThecodontosaurus();
    public static final Block FOSSIL_TIARAJUDENS = new BlockFossilTiarajudens();
    public static final Block FOSSIL_TIKTAALIK = new BlockFossilTiktaalik();
    public static final Block FOSSIL_TULLIMONSTRUM = new BlockFossilTullimonstrum();
    public static final Block FOSSIL_WALLISEROPS = new BlockFossilWalliserops();
    public static final Block FOSSIL_YINLONG = new BlockFossilYinlong();
    public static final Block FOSSIL_JONKERIA = new BlockFossilJonkeria();
    public static final Block FOSSIL_POSTOSUCHUS = new BlockFossilPostosuchus();
    public static final Block FOSSIL_CRASSIGYRINUS = new BlockFossilCrassigyrinus();
    public static final Block FOSSIL_ERYOPS = new BlockFossilEryops();
    public static final Block FOSSIL_LESSEMSAURUS = new BlockFossilLessemsaurus();
    public static final Block FOSSIL_NOTHOSAURUS = new BlockFossilNothosaurus();
    public static final Block FOSSIL_ATOPODENTATUS = new BlockFossilAtopodentatus();
    public static final Block FOSSIL_PLACODUS = new BlockFossilPlacodus();
    public static final Block FOSSIL_SHONISAURUS = new BlockFossilShonisaurus();
    public static final Block FOSSIL_LISOWICIA = new BlockFossilLisowicia();
    public static final Block FOSSIL_SMILOSUCHUS = new BlockFossilSmilosuchus();
    public static final Block FOSSIL_EORHYNCHOCHELYS = new BlockFossilEorhynchochelys();
    public static final Block FOSSIL_DATHEOSAURUS = new BlockFossilDatheosaurus();
    public static final Block FOSSIL_PHOLIDERPETON = new BlockFossilPholiderpeton();
    public static final Block FOSSIL_MEGALOCEPHALUS = new BlockFossilMegalocephalus();
    public static final Block FOSSIL_LIMNOSCELIS = new BlockFossilLimnoscelis();
    public static final Block FOSSIL_PROBURNETIA = new BlockFossilProburnetia();
    public static final Block FOSSIL_TETRACERATOPS  = new BlockFossilTetraceratops();
    public static final Block FOSSIL_BUNOSTEGOS  = new BlockFossilBunostegos();
    public static final Block FOSSIL_INOSTRANCEVIA  = new BlockFossilInostrancevia();
    public static final Block FOSSIL_TURBOSCINETES  = new BlockFossilTurboscinetes();
    public static final Block FOSSIL_AEGER  = new BlockFossilAeger();
    public static final Block FOSSIL_ERYON  = new BlockFossilEryon();
    public static final Block FOSSIL_FOREYIA  = new BlockFossilForeyia();
    public static final Block FOSSIL_CROTALOCEPHALUS  = new BlockFossilCrotalocephalus();
    public static final Block FOSSIL_OPABINIA  = new BlockFossilOpabinia();
    public static final Block FOSSIL_GEMUENDINA  = new BlockFossilGemuendina();
    public static final Block FOSSIL_BOBASATRANIA  = new BlockFossilBobasatrania();
    public static final Block FOSSIL_OTTOIA  = new BlockFossilOttoia();
    public static final Block FOSSIL_BELANTSEA  = new BlockFossilBelantsea();
    public static final Block FOSSIL_CRINOID_RAFT  = new BlockFossilCrinoidRaft();

}
